# What is Pandas?
Pandas is an open-source Python library used for data manipulation, data analysis, and data cleaning.

It provides fast, flexible, and easy-to-use data structures such as:

- Series (1D)
- DataFrame (2D)

Pandas is one of the most important libraries for Data Science, Machine Learning, Artificial Intelligence, and Data Analysis.

# Why Use Pandas?

Pandas helps us:

- Read datasets
- Clean data
- Analyze data
- Filter data
- Sort data
- Handle missing values
- Perform statistical analysis
- Prepare data for Machine Learning

# Features of Pandas

- Fast and Efficient
- Easy Data Manipulation
- Powerful Data Analysis
- Missing Value Handling
- Supports CSV, Excel, JSON, SQL
- Grouping and Aggregation
- Data Cleaning
- Time Series Support

# Import Pandas

In [1]:
import pandas as pd

## Check Pandas Version

# Pandas Data Structures

Pandas provides two main data structures:

## 1. Series

A one-dimensional labeled array.

Example:

10

20

30

40

---

## 2. DataFrame

A two-dimensional table containing rows and columns.

Example:

| Name | Age |
|------|-----|
| Ali | 20 |
| Sara | 22 |

# 📊 Loading and Exploring the Titanic Dataset

## Objective


Dataset Used: Titanic Dataset

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")

# Display the First Five Rows

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# Display the Last Rows

In [4]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

# Random Sample

In [5]:
df.sample(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
744,1,3,male,31.0,0,0,7.925,S,Third,man,True,NaN,Southampton,yes,True
520,1,1,female,30.0,0,0,93.500,S,First,woman,False,B,Southampton,yes,True
647,1,1,male,56.0,0,0,35.500,C,First,man,True,A,Cherbourg,yes,True
393,1,1,female,23.0,1,0,113.275,C,First,woman,False,D,Cherbourg,yes,False
360,0,3,male,40.0,1,4,27.900,S,Third,man,True,NaN,Southampton,no,False

# Shape of Dataset

In [6]:
df.shape

(891, 15)

# Number of Elements

In [7]:
df.size

13365

# Number of Dimensions

In [8]:
df.ndim

2

# Column Names

In [9]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

# Row Index

In [10]:
df.index

RangeIndex(start=0, stop=891, step=1)

# Data Types

In [11]:
df.dtypes

survived         int64
pclass           int64
sex                str
age            float64
sibsp            int64
parch            int64
fare           float64
embarked           str
class              str
who                str
adult_male        bool
deck               str
embark_town        str
alive              str
alone             bool
dtype: object

# Dataset Information

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.4 KB

# Statistical Summary

In [13]:
df.describe()   # Statistics for numeric columns.
df.describe(include="all")    #Statistics for all columns.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Check if Dataset is Empty

In [14]:
df.empty   #  returns false because the Titanic dataset contains data.

False

# Dataset have null values

In [15]:
df.isnull

<bound method DataFrame.isnull of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]>

# SUM of total null values in each column

In [16]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# Select a Single Column

In [17]:
# Select the survived column
df["survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [18]:
# Select the passenger class column
df["pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int64

In [19]:
# Select the gender column
df["sex"]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: str

In [20]:
# Select the age column
df["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [21]:
# Select the class column
df["class"]

0       Third
1       First
2       Third
3       First
4       Third
        ...
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: str

In [22]:
# Check the data type of the selected column
type(df["age"])

pandas.Series

In [23]:
# Display the first 10 values of the age column
df["age"].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: age, dtype: float64

In [24]:
# Count total values in the age column
df["age"].count()

np.int64(714)

In [25]:
# Count missing values in the age column
df["age"].isnull().sum()

np.int64(177)

# Select Multiple Columns

In [26]:
# Select age and fare columns
df[["age", "fare"]]

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [27]:
# Select survived, sex and class
df[["survived", "sex", "class"]]

     survived     sex   class
0           0    male   Third
1           1  female   First
2           1  female   Third
3           1  female   First
4           0    male   Third
..        ...     ...     ...
886         0    male  Second
887         1  female   First
888         0  female   Third
889         1    male   First
890         0    male   Third

[891 rows x 3 columns]

In [28]:
# Select pclass, age, fare
df[["pclass", "age", "fare"]]

     pclass   age     fare
0         3  22.0   7.2500
1         1  38.0  71.2833
2         3  26.0   7.9250
3         1  35.0  53.1000
4         3  35.0   8.0500
..      ...   ...      ...
886       2  27.0  13.0000
887       1  19.0  30.0000
888       3   NaN  23.4500
889       1  26.0  30.0000
890       3  32.0   7.7500

[891 rows x 3 columns]

In [29]:
# Select who, alone and adult_male
df[["who", "alone", "adult_male"]]

       who  alone  adult_male
0      man  False        True
1    woman  False       False
2    woman   True       False
3    woman  False       False
4      man   True        True
..     ...    ...         ...
886    man   True        True
887  woman   True       False
888  woman  False       False
889    man   True        True
890    man   True        True

[891 rows x 3 columns]

In [30]:
# Select embarked and embark town
df[["embarked", "embark_town"]]

    embarked  embark_town
0          S  Southampton
1          C    Cherbourg
2          S  Southampton
3          S  Southampton
4          S  Southampton
..       ...          ...
886        S  Southampton
887        S  Southampton
888        S  Southampton
889        C    Cherbourg
890        Q   Queenstown

[891 rows x 2 columns]

In [31]:
# Check the data type
type(df[["age", "fare"]])

pandas.DataFrame

In [32]:
df['age'].isnull().sum()

np.int64(177)

In [33]:
df["age"] = df["age"].fillna(df["age"].ffill())

In [34]:
df['age'].isnull().sum()

np.int64(0)

# Selecting Rows

Rows can be selected using slicing.

In [35]:
# Display the first 5 rows
df[0:5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [36]:
# Display the first 10 rows
df[0:10]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [37]:
# Display rows from index 10 to 20
df[10:21]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,2.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,31.0,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True

In [38]:
# Display every third row from the first 30 rows
df[:30:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False

In [39]:
# Display rows from index 30 to 60 with a step of 5
df[30:61:5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
45,0,3,male,19.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
50,0,3,male,7.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
55,1,1,male,65.0,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
60,0,3,male,22.0,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True

# Understanding Row Slicing

Row slicing follows this pattern:

df[start : end : step]

Where:

- start → Starting row index
- end → Ending row index (excluded)
- step → Interval between rows

In [40]:
# Display the first 25 rows
df[:25]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,2.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,31.0,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [41]:
# Display rows from index 40 to 55
df[40:56]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
42,0,3,male,27.0,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
44,1,3,female,19.0,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
45,0,3,male,19.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
46,0,3,male,19.0,1,0,15.5000,Q,Third,man,True,NaN,Queenstown,no,False
47,1,3,female,19.0,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
48,0,3,male,19.0,2,0,21.6792,C,Third,man,True,NaN,Cherbourg,no,False
49,0,3,female,18.0,1,0,17.8000,S,Third,woman,False,NaN,Southampton,no,False
50,0,3,male,7.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
51,0,3,male,21.0,0,0,7.8000,S,Third,man,True,NaN,Southampton,no,True
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
53,1,2,female,29.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
55,1,1,male,65.0,0,0,35.5000,S,First,man,True,C,Southampton,yes,True

In [42]:
# Display the last 15 rows
df[-15:]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
876,0,3,male,20.0,0,0,9.8458,S,Third,man,True,NaN,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [43]:
# Display every fifth row
df[::5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# Selecting Data Using loc[]

The `loc[]` method is used to select rows and columns using **labels** (row labels and column names).

### Syntax

df.loc[row_label, column_label]

`loc[]` includes both the start and end labels when slicing.

In [44]:
# Display the first row
df.loc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [45]:
# Display row with index 5
df.loc[5]

survived                0
pclass                  3
sex                  male
age                  35.0
sibsp                   0
parch                   0
fare               8.4583
embarked                Q
class               Third
who                   man
adult_male           True
deck                  NaN
embark_town    Queenstown
alive                  no
alone                True
Name: 5, dtype: object

In [46]:
# Display rows from index 0 to 10
df.loc[0:10]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False

In [47]:
# Select only the age column
df.loc[:, "age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    19.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [48]:
# Select only the fare column
df.loc[:, "fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 891, dtype: float64

In [49]:
# Select age, sex and class columns
df.loc[:, ["age", "sex", "class"]]

      age     sex   class
0    22.0    male   Third
1    38.0  female   First
2    26.0  female   Third
3    35.0  female   First
4    35.0    male   Third
..    ...     ...     ...
886  27.0    male  Second
887  19.0  female   First
888  19.0  female   Third
889  26.0    male   First
890  32.0    male   Third

[891 rows x 3 columns]

In [50]:
# Select rows 0 to 10 and multiple columns
df.loc[0:10, ["age", "sex", "fare"]]

     age     sex     fare
0   22.0    male   7.2500
1   38.0  female  71.2833
2   26.0  female   7.9250
3   35.0  female  53.1000
4   35.0    male   8.0500
5   35.0    male   8.4583
6   54.0    male  51.8625
7    2.0    male  21.0750
8   27.0  female  11.1333
9   14.0  female  30.0708
10   4.0  female  16.7000

In [51]:
# Select a single value
df.loc[5, "fare"]

np.float64(8.4583)

In [52]:
# Select all rows with selected columns
df.loc[:, ["survived", "sex", "age", "fare"]]

     survived     sex   age     fare
0           0    male  22.0   7.2500
1           1  female  38.0  71.2833
2           1  female  26.0   7.9250
3           1  female  35.0  53.1000
4           0    male  35.0   8.0500
..        ...     ...   ...      ...
886         0    male  27.0  13.0000
887         1  female  19.0  30.0000
888         0  female  19.0  23.4500
889         1    male  26.0  30.0000
890         0    male  32.0   7.7500

[891 rows x 4 columns]

In [53]:
# Display a single value from row 100 and fare column
df.loc[100, "fare"]

np.float64(7.8958)

In [54]:
df["deck"]=df["deck"].fillna(df["deck"].bfill())

In [55]:
print(df['sex'].unique())   # ['male', 'female']
print(df['sex'].nunique())  # 2
print(df['sex'].value_counts())

<StringArray>
['male', 'female']
Length: 2, dtype: str
2
sex
male      577
female    314
Name: count, dtype: int64

In [56]:
# Column names ki list
df.columns.tolist()

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

In [57]:
df.drop(["class", "who","alive"],axis=1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,True,C,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,False,C,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,True,E,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,True,B,Southampton,True
887,1,1,female,19.0,0,0,30.0000,S,False,B,Southampton,True
888,0,3,female,19.0,1,2,23.4500,S,False,C,Southampton,False
889,1,1,male,26.0,0,0,30.0000,C,True,C,Cherbourg,True
890,0,3,male,32.0,0,0,7.7500,Q,True,NaN,Queenstown,True

# 📊 Filtering Data in Pandas

# Filter Using
## Equal To (==)

The == operator is used to select rows that exactly match a value.

In [58]:
# Show all passengers who survived
df[df["survived"] == 1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,G,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,C,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,B,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [59]:
# Show all passengers who did not survive
df[df["survived"] == 0]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,B,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [60]:
# Show all male passengers
df[df["sex"] == "male"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,B,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [61]:
# Show all male passengers
df[df["sex"] == "male"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,B,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [62]:
# Show passengers travelling in First Class
df[df["class"] == "First"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [63]:
# Show passengers travelling in Third Class
df[df["class"] == "Third"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,B,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,B,Queenstown,no,False
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True


# 2. Not Equal (!=)
## Filter Using Not Equal (!=)

In [64]:
# Show passengers except males
df[df["sex"] != "male"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,G,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,B,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,B,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,B,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False

In [65]:
# Show passengers except First Class
df[df["class"] != "First"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,B,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

#3. Greater Than (>)

# Filter Using Greater Than (>)

In [66]:
# Age greater than 30
df[df["age"] > 30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,C,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,B,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,B,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [67]:
# Fare greater than 100
df[df["fare"] > 100]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,40.00,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,E,Cherbourg,yes,True
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
299,1,1,female,50.00,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
306,1,1,female,0.92,0,0,110.8833,C,First,woman,False,C,Cherbourg,yes,True
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.00,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.00,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
332,0,1,male,38.00,0,1,153.4625,S,First,man,True,C,Southampton,no,False
334,1,1,female,16.00,1,0,133.6500,S,First,woman,False,C,Southampton,yes,False
337,1,1,female,41.00,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,C,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
380,1,1,female,42.00,0,0,227.5250,C,First,woman,False,B,Cherbourg,yes,True
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
438,0,1,male,64.00,1,4,263.0000,S,First,man,True,C,Southampton,no,False
498,0,1,female,25.00,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
527,0,1,male,50.00,0,0,221.7792,S,First,man,True,C,Southampton,no,True
537,1,1,female,30.00,0,0,106.4250,C,First,woman,False,B,Cherbourg,yes,True
544,0,1,male,50.00,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
557,0,1,male,48.00,0,0,227.5250,C,First,man,True,E,Cherbourg,no,True
581,1,1,female,39.00,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.00,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
659,0,1,male,58.00,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,E,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,C,Southampton,yes,True
716,1,1,female,38.00,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.00,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
856,1,1,female,45.00,1,1,164.8667,S,First,woman,False,E,Southampton,yes,False

In [68]:
# Age greater than 60
df[df["age"] > 60]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,D,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
55,1,1,male,65.0,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,B,Queenstown,no,True
170,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
252,0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
280,0,3,male,65.0,0,0,7.7500,Q,Third,man,True,A,Queenstown,no,True
326,0,3,male,61.0,0,0,6.2375,S,Third,man,True,D,Southampton,no,True
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
456,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
457,1,1,female,65.0,1,0,51.8625,S,First,woman,False,D,Southampton,yes,False
483,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,B,Southampton,yes,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,D,Cherbourg,no,True
545,0,1,male,64.0,0,0,26.0000,S,First,man,True,C,Southampton,no,True
555,0,1,male,62.0,0,0,26.5500,S,First,man,True,A,Southampton,no,True
570,1,2,male,62.0,0,0,10.5000,S,Second,man,True,C,Southampton,yes,True
625,0,1,male,61.0,0,0,32.3208,S,First,man,True,D,Southampton,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,B,Southampton,no,True
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,D,Southampton,no,True

# 4. Less Than (<)

In [69]:
# Age less than 18
df[df["age"] < 18]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,G,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,D,Southampton,no,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,D,Queenstown,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,0,3,male,4.0,4,2,31.2750,S,Third,child,False,D,Southampton,no,False
852,0,3,female,9.0,1,1,15.2458,C,Third,child,False,D,Cherbourg,no,False
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,D,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,C,Cherbourg,yes,True

In [70]:
# Fare less than 20
df[df["fare"] < 20]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,B,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,B,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# 5. Greater Than Equal (>=)

In [71]:
# Age greater than or equal to 50
df[df["age"] >= 50]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,D,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,D,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,1,1,female,52.0,1,1,93.5000,S,First,woman,False,B,Southampton,yes,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,D,Southampton,no,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [72]:
# Fare greater than or equal to 50
df[df["fare"] >= 50]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,40.0,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,E,Southampton,yes,False
863,0,3,female,48.0,8,2,69.5500,S,Third,woman,False,A,Southampton,no,False
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

# 6. Less Than Equal (<=)

In [73]:
# Age less than or equal to 10
df[df["age"] <= 10]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,G,Southampton,no,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,D,Queenstown,no,False
17,1,2,male,2.00,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
24,0,3,female,8.00,3,1,21.0750,S,Third,child,False,C,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,E,Southampton,yes,False
832,0,3,male,0.83,0,0,7.2292,C,Third,man,True,E,Cherbourg,no,True
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,D,Southampton,no,False
852,0,3,female,9.00,1,1,15.2458,C,Third,child,False,D,Cherbourg,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,D,Southampton,yes,False

In [74]:
# Fare less than or equal to 15
df[df["fare"] <= 15]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,B,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,B,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# 7. Multiple Conditions (&)

In [75]:
# Female passengers who survived
df[(df["sex"] == "female") & (df["survived"] == 1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,G,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,C,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,C,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,B,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [76]:
df[(df["pclass"] == 1) & (df["sibsp"] == 0)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,B,Cherbourg,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [77]:
df[(df["pclass"] == 1) & (df["age"] <= 30) & (df["sex"] == "male")&(df["survived"] == 1) & (df["parch"] ==2)]
# df[(df["survived"] == 1) & (df["parch"] ==2)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False

In [78]:
# Male passengers older than 30
df[(df["sex"] == "male") & (df["age"] > 30)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,D,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,D,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868,0,3,male,31.0,0,0,9.5000,S,Third,man,True,D,Southampton,no,True
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,C,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,B,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [79]:
# Fare greater than 100 and age greater than 30
df[(df["fare"] > 100) & (df["age"] > 30)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
31,1,1,female,40.0,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
195,1,1,female,58.0,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,E,Cherbourg,yes,True
268,1,1,female,58.0,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.0,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
299,1,1,female,50.0,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.0,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.0,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.0,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
332,0,1,male,38.0,0,1,153.4625,S,First,man,True,C,Southampton,no,False
337,1,1,female,41.0,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
380,1,1,female,42.0,0,0,227.5250,C,First,woman,False,B,Cherbourg,yes,True
390,1,1,male,36.0,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
527,0,1,male,50.0,0,0,221.7792,S,First,man,True,C,Southampton,no,True
544,0,1,male,50.0,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
557,0,1,male,48.0,0,0,227.5250,C,First,man,True,E,Cherbourg,no,True
581,1,1,female,39.0,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.0,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
659,0,1,male,58.0,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.0,2,0,133.6500,S,First,man,True,E,Southampton,yes,False
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
698,0,1,male,49.0,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
716,1,1,female,38.0,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
763,1,1,female,36.0,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.0,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,E,Southampton,yes,False

In [80]:
df[(df["survived"] == 1) & (df["parch"] ==2)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
8,1,3,female,27.00,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,D,Cherbourg,yes,False
58,1,2,female,5.00,1,2,27.7500,S,Second,child,False,B,Southampton,yes,False
68,1,3,female,17.00,4,2,7.9250,S,Third,woman,False,F,Southampton,yes,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,C,Southampton,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
136,1,1,female,19.00,0,2,26.2833,S,First,woman,False,D,Southampton,yes,False
165,1,3,male,9.00,0,2,20.5250,S,Third,child,False,E,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,A,Southampton,yes,False
233,1,3,female,5.00,4,2,31.3875,S,Third,child,False,C,Southampton,yes,False
237,1,2,female,8.00,0,2,26.2500,S,Second,child,False,C,Southampton,yes,False
247,1,2,female,24.00,0,2,14.5000,S,Second,woman,False,D,Southampton,yes,False
255,1,3,female,29.00,0,2,15.2458,C,Third,woman,False,B,Cherbourg,yes,False
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,E,Southampton,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,B,Cherbourg,yes,False
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
394,1,3,female,24.00,0,2,16.7000,S,Third,woman,False,G,Southampton,yes,False
417,1,2,female,18.00,0,2,13.0000,S,Second,woman,False,E,Southampton,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
472,1,2,female,33.00,1,2,27.7500,S,Second,woman,False,D,Southampton,yes,False
506,1,2,female,33.00,0,2,26.0000,S,Second,woman,False,E,Southampton,yes,False
533,1,3,female,17.00,0,2,22.3583,C,Third,woman,False,B,Cherbourg,yes,False
535,1,2,female,7.00,0,2,26.2500,S,Second,child,False,B,Southampton,yes,False
539,1,1,female,22.00,0,2,49.5000,C,First,woman,False,B,Cherbourg,yes,False
540,1,1,female,36.00,0,2,71.0000,S,First,woman,False,B,Southampton,yes,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
585,1,1,female,18.00,0,2,79.6500,S,First,woman,False,E,Southampton,yes,False
608,1,2,female,22.00,1,2,41.5792,C,Second,woman,False,C,Cherbourg,yes,False
615,1,2,female,24.00,1,2,65.0000,S,Second,woman,False,F,Southampton,yes,False
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
754,1,2,female,48.00,1,2,65.0000,S,Second,woman,False,B,Southampton,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
827,1,2,male,1.00,0,2,37.0042,C,Second,child,False,B,Cherbourg,yes,False

In [81]:
def category(age):
    if age <= 20:
        return "child"
    elif age <=30 :
        return "adult"
    else :
         return "oldage"
df["category"]= df["age"].apply(category)

In [82]:
df.head(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True,oldage
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True,oldage
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,oldage
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False,child
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False,adult
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,G,Cherbourg,yes,False,child
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,child
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,oldage
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,D,Southampton,no,True,child
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,D,Southampton,no,False,oldage
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,D,Southampton,no,True,child
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,D,Southampton,yes,True,oldage
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,D,Queenstown,no,False,child
17,1,2,male,2.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True,child
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,D,Southampton,no,False,oldage
19,1,3,female,31.0,0,0,7.2250,C,Third,woman,False,D,Cherbourg,yes,True,oldage

# 8. OR Operator (|)

In [83]:
# Male OR Female (returns all rows)
df[(df["sex"] == "male") | (df["sex"] == "female")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True,oldage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True,adult
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,child
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False,child
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,adult
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,oldage

In [84]:
# First OR Second Class
df[(df["class"] == "First") | (df["class"] == "Second")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,oldage
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,G,Cherbourg,yes,False,child
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,oldage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,B,Southampton,yes,False,adult
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,B,Southampton,no,True,adult
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True,adult
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,child
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,adult

In [85]:
# Age less than 10 OR greater than 60
df[(df["age"] < 10) | (df["age"] > 60)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,G,Southampton,no,False,child
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,child
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,D,Queenstown,no,False,child
17,1,2,male,2.00,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True,child
24,0,3,female,8.00,3,1,21.0750,S,Third,child,False,C,Southampton,no,False,child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,0,3,male,0.83,0,0,7.2292,C,Third,man,True,E,Cherbourg,no,True,child
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,D,Southampton,no,False,child
851,0,3,male,74.00,0,0,7.7750,S,Third,man,True,D,Southampton,no,True,oldage
852,0,3,female,9.00,1,1,15.2458,C,Third,child,False,D,Cherbourg,no,False,child
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,D,Southampton,yes,False,child

# NOT Operator (~)

Reverses the condition.

In [86]:
# Passengers who are NOT male
df[~(df["sex"] == "male")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,G,Southampton,yes,False,adult
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,G,Cherbourg,yes,False,child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,B,Southampton,yes,False,adult
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,B,Southampton,no,True,adult
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,B,Queenstown,no,False,oldage
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,child
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False,child

In [87]:
# Passengers who did NOT survive
df[~(df["survived"] == 1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,adult
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True,oldage
5,0,3,male,35.0,0,0,8.4583,Q,Third,man,True,E,Queenstown,no,True,oldage
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,oldage
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,G,Southampton,no,False,child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,B,Southampton,no,True,adult
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,B,Queenstown,no,False,oldage
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,B,Southampton,no,True,adult
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,C,Southampton,no,False,child
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,oldage

# 📊 Adding, Updating and Deleting Columns in Pandas

In [88]:
# Add a new column with the same value for all passengers
df["country"] = "Pakistan"

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category,country
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,adult,Pakistan
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage,Pakistan
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,adult,Pakistan
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage,Pakistan
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True,oldage,Pakistan

In [89]:
# Add a new column for bonus fare
df["bonus_fare"] = 100

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category,country,bonus_fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,adult,Pakistan,100
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage,Pakistan,100
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,adult,Pakistan,100
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage,Pakistan,100
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True,oldage,Pakistan,100

In [90]:
# Add a new boolean column
df["checked"] = True

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category,country,bonus_fare,checked
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,adult,Pakistan,100,True
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage,Pakistan,100,True
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,adult,Pakistan,100,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage,Pakistan,100,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True,oldage,Pakistan,100,True

# Creating Calculated Columns

A new column can also be created using existing columns.

In [91]:
# Add 10 to every fare
df["updated_fare"] = df["fare"] + 10

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,category,country,bonus_fare,checked,updated_fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,adult,Pakistan,100,True,17.2500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,oldage,Pakistan,100,True,81.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,adult,Pakistan,100,True,17.9250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,oldage,Pakistan,100,True,63.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,E,Southampton,no,True,oldage,Pakistan,100,True,18.0500

In [92]:
# Double the fare
df["double_fare"] = df["fare"] * 2

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,deck,embark_town,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,C,Southampton,no,False,adult,Pakistan,100,True,17.2500,14.5000
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,C,Cherbourg,yes,False,oldage,Pakistan,100,True,81.2833,142.5666
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,C,Southampton,yes,True,adult,Pakistan,100,True,17.9250,15.8500
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,C,Southampton,yes,False,oldage,Pakistan,100,True,63.1000,106.2000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,E,Southampton,no,True,oldage,Pakistan,100,True,18.0500,16.1000

In [93]:
# Calculate family members
df["family_members"] = df["sibsp"] + df["parch"]

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,embark_town,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare,family_members
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,Southampton,no,False,adult,Pakistan,100,True,17.2500,14.5000,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,Cherbourg,yes,False,oldage,Pakistan,100,True,81.2833,142.5666,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,Southampton,yes,True,adult,Pakistan,100,True,17.9250,15.8500,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,Southampton,yes,False,oldage,Pakistan,100,True,63.1000,106.2000,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,Southampton,no,True,oldage,Pakistan,100,True,18.0500,16.1000,0

In [94]:
# Calculate total family including the passenger
df["family_size"] = df["sibsp"] + df["parch"] + 1

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare,family_members,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,no,False,adult,Pakistan,100,True,17.2500,14.5000,1,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,yes,False,oldage,Pakistan,100,True,81.2833,142.5666,1,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,yes,True,adult,Pakistan,100,True,17.9250,15.8500,0,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,yes,False,oldage,Pakistan,100,True,63.1000,106.2000,1,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,no,True,oldage,Pakistan,100,True,18.0500,16.1000,0,1

In [95]:
# Calculate total family including the passenger
df["family_size"] = df["sibsp"] + df["parch"] + 1

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare,family_members,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,no,False,adult,Pakistan,100,True,17.2500,14.5000,1,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,yes,False,oldage,Pakistan,100,True,81.2833,142.5666,1,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,yes,True,adult,Pakistan,100,True,17.9250,15.8500,0,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,yes,False,oldage,Pakistan,100,True,63.1000,106.2000,1,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,no,True,oldage,Pakistan,100,True,18.0500,16.1000,0,1

# Updating Existing Columns

In [96]:
# Increase fare by 20
df["fare"] = df["fare"] + 20

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare,family_members,family_size
0,0,3,male,22.0,1,0,27.2500,S,Third,man,...,no,False,adult,Pakistan,100,True,17.2500,14.5000,1,2
1,1,1,female,38.0,1,0,91.2833,C,First,woman,...,yes,False,oldage,Pakistan,100,True,81.2833,142.5666,1,2
2,1,3,female,26.0,0,0,27.9250,S,Third,woman,...,yes,True,adult,Pakistan,100,True,17.9250,15.8500,0,1
3,1,1,female,35.0,1,0,73.1000,S,First,woman,...,yes,False,oldage,Pakistan,100,True,63.1000,106.2000,1,2
4,0,3,male,35.0,0,0,28.0500,S,Third,man,...,no,True,oldage,Pakistan,100,True,18.0500,16.1000,0,1

In [97]:
# Convert survived values into strings
# df["survived"] = df["survived"].replace({
#     0: "No",
#     1: "Yes"
# })

# df.head()

 # Insert Column

In [98]:
df.insert(1, "Passenger_Number", range(1, len(df)+1))

df.head()

,survived,Passenger_Number,pclass,sex,age,sibsp,parch,fare,embarked,class,...,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare,family_members,family_size
0,0,1,3,male,22.0,1,0,27.2500,S,Third,...,no,False,adult,Pakistan,100,True,17.2500,14.5000,1,2
1,1,2,1,female,38.0,1,0,91.2833,C,First,...,yes,False,oldage,Pakistan,100,True,81.2833,142.5666,1,2
2,1,3,3,female,26.0,0,0,27.9250,S,Third,...,yes,True,adult,Pakistan,100,True,17.9250,15.8500,0,1
3,1,4,1,female,35.0,1,0,73.1000,S,First,...,yes,False,oldage,Pakistan,100,True,63.1000,106.2000,1,2
4,0,5,3,male,35.0,0,0,28.0500,S,Third,...,no,True,oldage,Pakistan,100,True,18.0500,16.1000,0,1

# Rename Columns

In [99]:
df.rename(columns={
    "sibsp": "siblings_spouses",
    "parch": "parents_children"
})

,survived,Passenger_Number,pclass,sex,age,siblings_spouses,parents_children,fare,embarked,class,...,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare,family_members,family_size
0,0,1,3,male,22.0,1,0,27.2500,S,Third,...,no,False,adult,Pakistan,100,True,17.2500,14.5000,1,2
1,1,2,1,female,38.0,1,0,91.2833,C,First,...,yes,False,oldage,Pakistan,100,True,81.2833,142.5666,1,2
2,1,3,3,female,26.0,0,0,27.9250,S,Third,...,yes,True,adult,Pakistan,100,True,17.9250,15.8500,0,1
3,1,4,1,female,35.0,1,0,73.1000,S,First,...,yes,False,oldage,Pakistan,100,True,63.1000,106.2000,1,2
4,0,5,3,male,35.0,0,0,28.0500,S,Third,...,no,True,oldage,Pakistan,100,True,18.0500,16.1000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,887,2,male,27.0,0,0,33.0000,S,Second,...,no,True,adult,Pakistan,100,True,23.0000,26.0000,0,1
887,1,888,1,female,19.0,0,0,50.0000,S,First,...,yes,True,child,Pakistan,100,True,40.0000,60.0000,0,1
888,0,889,3,female,19.0,1,2,43.4500,S,Third,...,no,False,child,Pakistan,100,True,33.4500,46.9000,3,4
889,1,890,1,male,26.0,0,0,50.0000,C,First,...,yes,True,adult,Pakistan,100,True,40.0000,60.0000,0,1
890,0,891,3,male,32.0,0,0,27.7500,Q,Third,...,no,True,oldage,Pakistan,100,True,17.7500,15.5000,0,1

In [100]:
df.rename(columns={
    "fare": "ticket_fare"
}, inplace=True)

df.head()

,survived,Passenger_Number,pclass,sex,age,sibsp,parch,ticket_fare,embarked,class,...,alive,alone,category,country,bonus_fare,checked,updated_fare,double_fare,family_members,family_size
0,0,1,3,male,22.0,1,0,27.2500,S,Third,...,no,False,adult,Pakistan,100,True,17.2500,14.5000,1,2
1,1,2,1,female,38.0,1,0,91.2833,C,First,...,yes,False,oldage,Pakistan,100,True,81.2833,142.5666,1,2
2,1,3,3,female,26.0,0,0,27.9250,S,Third,...,yes,True,adult,Pakistan,100,True,17.9250,15.8500,0,1
3,1,4,1,female,35.0,1,0,73.1000,S,First,...,yes,False,oldage,Pakistan,100,True,63.1000,106.2000,1,2
4,0,5,3,male,35.0,0,0,28.0500,S,Third,...,no,True,oldage,Pakistan,100,True,18.0500,16.1000,0,1

# Delete Columns using drop()

In [101]:
df.drop("country", axis=1)

,survived,Passenger_Number,pclass,sex,age,sibsp,parch,ticket_fare,embarked,class,...,embark_town,alive,alone,category,bonus_fare,checked,updated_fare,double_fare,family_members,family_size
0,0,1,3,male,22.0,1,0,27.2500,S,Third,...,Southampton,no,False,adult,100,True,17.2500,14.5000,1,2
1,1,2,1,female,38.0,1,0,91.2833,C,First,...,Cherbourg,yes,False,oldage,100,True,81.2833,142.5666,1,2
2,1,3,3,female,26.0,0,0,27.9250,S,Third,...,Southampton,yes,True,adult,100,True,17.9250,15.8500,0,1
3,1,4,1,female,35.0,1,0,73.1000,S,First,...,Southampton,yes,False,oldage,100,True,63.1000,106.2000,1,2
4,0,5,3,male,35.0,0,0,28.0500,S,Third,...,Southampton,no,True,oldage,100,True,18.0500,16.1000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,887,2,male,27.0,0,0,33.0000,S,Second,...,Southampton,no,True,adult,100,True,23.0000,26.0000,0,1
887,1,888,1,female,19.0,0,0,50.0000,S,First,...,Southampton,yes,True,child,100,True,40.0000,60.0000,0,1
888,0,889,3,female,19.0,1,2,43.4500,S,Third,...,Southampton,no,False,child,100,True,33.4500,46.9000,3,4
889,1,890,1,male,26.0,0,0,50.0000,C,First,...,Cherbourg,yes,True,adult,100,True,40.0000,60.0000,0,1
890,0,891,3,male,32.0,0,0,27.7500,Q,Third,...,Queenstown,no,True,oldage,100,True,17.7500,15.5000,0,1

In [102]:
df.drop(["checked", "bonus_fare"], axis=1)

,survived,Passenger_Number,pclass,sex,age,sibsp,parch,ticket_fare,embarked,class,...,deck,embark_town,alive,alone,category,country,updated_fare,double_fare,family_members,family_size
0,0,1,3,male,22.0,1,0,27.2500,S,Third,...,C,Southampton,no,False,adult,Pakistan,17.2500,14.5000,1,2
1,1,2,1,female,38.0,1,0,91.2833,C,First,...,C,Cherbourg,yes,False,oldage,Pakistan,81.2833,142.5666,1,2
2,1,3,3,female,26.0,0,0,27.9250,S,Third,...,C,Southampton,yes,True,adult,Pakistan,17.9250,15.8500,0,1
3,1,4,1,female,35.0,1,0,73.1000,S,First,...,C,Southampton,yes,False,oldage,Pakistan,63.1000,106.2000,1,2
4,0,5,3,male,35.0,0,0,28.0500,S,Third,...,E,Southampton,no,True,oldage,Pakistan,18.0500,16.1000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,887,2,male,27.0,0,0,33.0000,S,Second,...,B,Southampton,no,True,adult,Pakistan,23.0000,26.0000,0,1
887,1,888,1,female,19.0,0,0,50.0000,S,First,...,B,Southampton,yes,True,child,Pakistan,40.0000,60.0000,0,1
888,0,889,3,female,19.0,1,2,43.4500,S,Third,...,C,Southampton,no,False,child,Pakistan,33.4500,46.9000,3,4
889,1,890,1,male,26.0,0,0,50.0000,C,First,...,C,Cherbourg,yes,True,adult,Pakistan,40.0000,60.0000,0,1
890,0,891,3,male,32.0,0,0,27.7500,Q,Third,...,NaN,Queenstown,no,True,oldage,Pakistan,17.7500,15.5000,0,1

In [103]:
df.drop(columns=["updated_fare"])

,survived,Passenger_Number,pclass,sex,age,sibsp,parch,ticket_fare,embarked,class,...,embark_town,alive,alone,category,country,bonus_fare,checked,double_fare,family_members,family_size
0,0,1,3,male,22.0,1,0,27.2500,S,Third,...,Southampton,no,False,adult,Pakistan,100,True,14.5000,1,2
1,1,2,1,female,38.0,1,0,91.2833,C,First,...,Cherbourg,yes,False,oldage,Pakistan,100,True,142.5666,1,2
2,1,3,3,female,26.0,0,0,27.9250,S,Third,...,Southampton,yes,True,adult,Pakistan,100,True,15.8500,0,1
3,1,4,1,female,35.0,1,0,73.1000,S,First,...,Southampton,yes,False,oldage,Pakistan,100,True,106.2000,1,2
4,0,5,3,male,35.0,0,0,28.0500,S,Third,...,Southampton,no,True,oldage,Pakistan,100,True,16.1000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,887,2,male,27.0,0,0,33.0000,S,Second,...,Southampton,no,True,adult,Pakistan,100,True,26.0000,0,1
887,1,888,1,female,19.0,0,0,50.0000,S,First,...,Southampton,yes,True,child,Pakistan,100,True,60.0000,0,1
888,0,889,3,female,19.0,1,2,43.4500,S,Third,...,Southampton,no,False,child,Pakistan,100,True,46.9000,3,4
889,1,890,1,male,26.0,0,0,50.0000,C,First,...,Cherbourg,yes,True,adult,Pakistan,100,True,60.0000,0,1
890,0,891,3,male,32.0,0,0,27.7500,Q,Third,...,Queenstown,no,True,oldage,Pakistan,100,True,15.5000,0,1

# Handling Missing Values in Pandas

Missing values are empty or unavailable values in a dataset.

In Pandas, missing values are usually represented as:

- NaN
- None
- NaT

Titanic dataset mein important missing columns:

- age
- deck
- embark_town

In [ ]:
# 1. Check Missing Values
df.isnull()

In [ ]:

df.isnull().sum()
# True  = Missing Value
# False = Value Available

In [ ]:
# 2. Missing Values Percentage ⭐
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100
missing_percentage

In [ ]:
# 2nd way 
missing_data = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_data

In [ ]:
# 3. Check Specific Column
df["age"].isnull().sum()
df["deck"].isnull().sum()
df["embark_town"].isnull().sum()

In [ ]:
# Select Rows with Missing Age
df[df["age"].isnull()]

In [ ]:
# dropna() — Remove Missing Rows
# Remove rows where ANY value is missing:
df.dropna()

In [ ]:
# Remove rows only if Age is missing:
df.dropna(subset=["age"])

In [ ]:
#Remove rows if Age OR Embark Town is missing:
df.dropna(subset=["age", "embark_town"])

In [ ]:
# 7. fillna() — Fill Missing Values
# Fill Age with Mean
mean_age = df["age"].mean()

df["age"] = df["age"].fillna(mean_age)

In [ ]:
#Fill Age with Median 
median_age = df["age"].median()

df["age"] = df["age"].fillna(median_age)

In [ ]:
# 8. ffill() — Forward Fill

# Previous value se missing value fill hoti hai.

df["age"] = df["age"].ffill()

In [ ]:
# 9. bfill() — Backward Fill

# Next available value se missing value fill hoti hai.

df["age"] = df["age"].bfill()

In [ ]:
# interpolate()
# Values ke beech estimated value fill karta hai.

df["age"] = df["age"].interpolate()

# GroupBy and Aggregation in Pandas

groupby() is used to divide data into groups.
Aggregation functions are used to calculate:

- count
- sum
- mean
- median
- minimum
- maximum
- standard deviation

In [ ]:
# Group by Sex
df.groupby("sex")
# Usually hum aggregation ke saath use karte hain:
df.groupby("sex")["survived"].mean()

In [ ]:
# Count Passengers by Class
df.groupby("class").size()
# or 2nd methoddddddddddd
df["class"].value_counts()

In [ ]:
# Average Age by Class
df.groupby("class")["age"].mean()

In [ ]:
# Average Fare by Class
df.groupby("class")["fare"].mean()

In [ ]:
#Multiple Aggregations
df.groupby("class")["fare"].agg([
    "count",
    "mean",
    "median",
    "min",
    "max"
])

In [ ]:
# Different Aggregations on Different Columns ⭐⭐⭐
df.groupby("class").agg({
    "age": "mean",
    "fare": "mean",
    "survived": "mean"
})

In [ ]:
# GroupBy + Multiple Aggregations
df.groupby(["sex", "class"]).agg({
    "survived": ["count", "mean"],
    "age": "mean",
    "fare": "mean"
})

In [ ]:
# Mean
# Average value:

df["age"].mean()
df["fare"].mean()

In [ ]:
# Median

# Middle value:

df["age"].median()
df["fare"].median()

In [ ]:
# Minimum and Maximum
df["age"].min()
df["age"].max()
df["fare"].min()
df["fare"].max()

In [ ]:
# Standard Deviation

# Data kitna spread hai:

df["age"].std()
df["fare"].std(

In [ ]:
# Variance
df["age"].var()
df["fare"].var()

In [ ]:
# Quantile

# 25%:

df["age"].quantile(0.25)

# 50%:

df["age"].quantile(0.50)

# 75%:

df["age"].quantile(0.75)

# Multiple quantiles:

df["age"].quantile([0.25, 0.50, 0.75])

In [ ]:
# Correlation 
df[["age", "fare", "survived"]].corr()

# Correlation ka range:

# -1  → Strong Negative Relationship
#  0  → No Relationship
# +1  → Strong Positive Relationship

In [ ]:
# Covariance
df[["age", "fare", "survived"]].cov()

In [ ]:
# Complete Statistical Summary
df.describe()

# Specific columns:

df[["age", "fare"]].describe()

In [ ]:

df.to_csv("traintitanic.csv", index=False)